owner: "55268446"
team: "16168828"
lastUpdatedBy: "55268446"
lastRevision: 1781247397000
name: api-stgs-pnc
color: null
values:
  - key: base_url
    value: ""
    enabled: true
  - key: token
    value: ""
    enabled: true
createdAt: 2026-06-04T06:33:07.000Z
updatedAt: 2026-06-12T06:56:37.000Z
