name: api-stgs-pnc
values:
  - key: base_url
    value: ''
  - key: token
    value: ''
  - key: refreshToken
    value: ''
  - key: caseId
    value: ''
  - key: reportId
    value: ''
  - key: caseId
    value: ''
  - key: teacherId
    value: ''
  - key: studentId
    value: ''
  - key: termId
    value: ''
color: 0
