name: PNC-SPTS - Development
values:
  - key: base_url
    value: 'http://dev.pnc-spts.example.com/api'
  - key: access_token
    value: ''
  - key: refresh_token
    value: ''
  - key: current_user_id
    value: ''
  - key: test_user_id
    value: ''
  - key: test_role_id
    value: ''
  - key: reset_token
    value: ''
  - key: superadmin_email
    value: superadmin@example.com
  - key: superadmin_password
    value: ''
  - key: admin_email
    value: admin@example.com
  - key: admin_password
    value: ''
  - key: tutor_email
    value: tutor@example.com
  - key: tutor_password
    value: ''
  - key: token
    value: ''
  - key: refreshToken
    value: ''
  - key: teacherId
    value: ''
color: 0
