ALTER TABLE `auth_users`
ADD COLUMN `first_name` VARCHAR(191) NOT NULL DEFAULT '',
ADD COLUMN `last_name` VARCHAR(191) NOT NULL DEFAULT '',
ADD COLUMN `phone` VARCHAR(191) NULL,
ADD COLUMN `status` ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'LOCKED') NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN `deletedAt` DATETIME(3) NULL;

CREATE UNIQUE INDEX `auth_users_phone_key` ON `auth_users`(`phone`);
