services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "npm run build &&
             npm run db:migrate &&
             npm run start:prod"
    env_file:
      - .env.staging
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:
